
package com.dream.utils.ip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IpAddressSearchWebServiceSoap", targetNamespace = "http://WebXml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IpAddressSearchWebServiceSoap {


    /**
     * <br /><h3>ͨ������IP��ַ��ѯ���ҡ����С������ߵ���Ϣ��û��ע�����ҵ�Ϊ�й�</h3><p>���������IP��ַ���Զ��滻 " ��" Ϊ "."�����������ݣ� һ��һά�ַ�������String(1)��String(0) = IP��ַ��String(1) = ��ѯ�������ʾ��Ϣ</p><br />
     * 
     * @param theIpAddress
     * @return
     *     returns com.dream.ip.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getCountryCityByIp")
    @WebResult(name = "getCountryCityByIpResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getCountryCityByIp", targetNamespace = "http://WebXml.com.cn/", className = "com.dream.ip.GetCountryCityByIp")
    @ResponseWrapper(localName = "getCountryCityByIpResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.dream.ip.GetCountryCityByIpResponse")
    public ArrayOfString getCountryCityByIp(
            @WebParam(name = "theIpAddress", targetNamespace = "http://WebXml.com.cn/")
                    String theIpAddress);

    /**
     * <br /><h3>�������IP��ַ�͵�ַ��Ϣ</h3><p>����������ޣ��������ݣ� һ��һά�ַ�������String(1)��String(0) = IP��ַ��String(1) = ��ַ��Ϣ</p><br />
     * 
     * @return
     *     returns com.dream.ip.ArrayOfString
     */
    @WebMethod(action = "http://WebXml.com.cn/getGeoIPContext")
    @WebResult(name = "getGeoIPContextResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getGeoIPContext", targetNamespace = "http://WebXml.com.cn/", className = "com.dream.ip.GetGeoIPContext")
    @ResponseWrapper(localName = "getGeoIPContextResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.dream.ip.GetGeoIPContextResponse")
    public ArrayOfString getGeoIPContext();

    /**
     * <br /><h3>��ñ�IP��ַ���� WEB ��������ݿ�汾����ʱ��</h3><p>����������ޣ�������� String</p><br />
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://WebXml.com.cn/getVersionTime")
    @WebResult(name = "getVersionTimeResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getVersionTime", targetNamespace = "http://WebXml.com.cn/", className = "com.dream.ip.GetVersionTime")
    @ResponseWrapper(localName = "getVersionTimeResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.dream.ip.GetVersionTimeResponse")
    public String getVersionTime();

}
